### ISSUE TITLE
Broken setLevel(logging.WARN) - and other levels as well

### ISSUE THREAD

**Issue by treahard** [Neopallium/lualogging#13]
Since upgrade to 1.3, you can no longer make the following types of calls:

logger:setLevel (logging.WARN)

You do not have access to logging.WARN (or DEBUG, etc.) as it is in a table you cannot access

If appender modules return only "logging" and not, for example, "logging.file", then it would work.  However, this would cause other modifications to be made.

**Comment by Neopallium** [comment]
new home: https://github.com/lunarmodules/lualogging
