### ISSUE TITLE
is this module still maintained?

### ISSUE THREAD

**Issue by Tieske** [Neopallium/lualogging#19]
@Neopallium do you still maintain this library? there are some good PR's that I'd like to use, but it looks like this project is abandoned.

**Comment by Tieske** [comment]
new home: https://github.com/lunarmodules/lualogging

**Comment by Neopallium** [comment]
Sorry, I haven't had time to work on my Lua projects.  Do you want to be the maintainer for LuaLogging?  I can archive this repo and post a link to your updated repo.

**Comment by Tieske** [comment]
yes, please do. The Luarocks entries have already been moved over as well

**Comment by Neopallium** [comment]
Updated Readme with link to the new home and will archive this repo.
